### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by Erry215** [mehdisadeghi/clashogram#3]
When I try to install clashogram by executing command `pip install clashogram` 
I receive this error:
 `Collecting clashogram
  Downloading https://files.pythonhosted.org/packages/0d/03/6e93ffce33acbbbd16ce4ed4e883b3328cb0a96f535855d0d87ad0db7b6c/Clashogram-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cWbym_/clashogram/setup.py", line 7, in <module>
        long_description=open('README.rst', encoding='utf-8').read(),
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cWbym_/clashogram/
`
How can I fix it?

**Comment by mehdisadeghi** [comment]
Please try with pip3 and python3 and let me know if it solves your problem.

Clashogram is a Python3 program.
