### ISSUE TITLE
Support "Not set" clan location

### ISSUE THREAD

**Issue by dosoft** [mehdisadeghi/clashogram#30]
If clan location is not set ("Not set" in the clan description) then clashogram fails with the following error:

Traceback (most recent call last):
  File "/opt/clashogram/venv/bin/clashogram", line 8, in <module>
    sys.exit(main())
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/clashogram/__main__.py", line 82, in main
    monitor.start()
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/clashogram/__main__.py", line 262, in start
    self.update()
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/clashogram/__main__.py", line 144, in update
    self.send_preparation_msg()
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/clashogram/__main__.py", line 173, in send_preparation_msg
    self.msg_factory.create_preparation_msg(),
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/clashogram/formatters.py", line 49, in create_preparation_msg
    oploc=op_extra_info.location,
  File "/opt/clashogram/venv/lib64/python3.6/site-packages/clashogram/models.py", line 11, in location
    return self.data['location']['name']
KeyError: 'location'

**Comment by mehdisadeghi** [comment]
Please try the master branch and feel free to reopen if not fixed.
