### ISSUE TITLE
Exception: Error calling CoC API: <Response [403]>

### ISSUE THREAD

**Issue by akula22** [mehdisadeghi/clashogram#31]
Traceback (most recent call last):
  File "/home/a/akula22/clashogram/myenv/bin/clashogram.py", line 747, in <module>
    main()
  File "/home/a/akula22/clashogram/myenv/lib/python3.4/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/a/akula22/clashogram/myenv/lib/python3.4/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/a/akula22/clashogram/myenv/lib/python3.4/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/a/akula22/clashogram/myenv/lib/python3.4/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/a/akula22/clashogram/myenv/bin/clashogram.py", line 53, in main
    monitor_currentwar(coc_token, clan_tag, bot_token, channel_name, forever, mute_attacks)
  File "/home/a/akula22/clashogram/myenv/bin/clashogram.py", line 64, in monitor_currentwar
    warinfo = coc_api.get_currentwar(clan_tag)
  File "/home/a/akula22/clashogram/myenv/bin/clashogram.py", line 151, in get_currentwar
    return WarInfo(self.call_api(self.get_currentwar_endpoint(clan_tag)))
  File "/home/a/akula22/clashogram/myenv/bin/clashogram.py", line 163, in call_api
    raise Exception('Error calling CoC API: %s' % res)
Exception: Error calling CoC API: <Response [403]>

or 
Exception: Error calling CoC API: <Response [404]>

help plz   можно по русски?

**Comment by mehdisadeghi** [comment]
Make sure your Token is correct and your IP address has not changed (if so, get a new token).

**Comment by mehdisadeghi** [comment]
Closing as can't reproduce anymore (after substantial recent changes). Feel free to reopen if it ever happens again.
